# Generated by Django 4.2.4 on 2023-10-07 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='Home-Banner/')),
                ('headline', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
