# Generated by Django 4.2.4 on 2023-10-07 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='subheadline',
            field=models.TextField(blank=True, null=True),
        ),
    ]
