# Generated by Django 4.2.4 on 2023-10-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_banner_subheadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactEnquires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=14)),
                ('comapny_name', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
