# Generated by Django 4.2.4 on 2023-10-08 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_contactenquires'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactenquires',
            old_name='comapny_name',
            new_name='company_name',
        ),
    ]
