# Generated by Django 4.2.4 on 2023-10-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_rename_comapny_name_contactenquires_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactenquires',
            name='company_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
