# Generated by Django 4.2.4 on 2023-10-08 15:58

import ckeditor.fields
from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
        ('Home', '0005_alter_contactenquires_company_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('thumbnail', models.ImageField(upload_to='Article-Thumbnail/')),
                ('writer', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField()),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('meta_tags', models.TextField()),
                ('meta_description', models.TextField()),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
