# Generated by Django 4.2.4 on 2023-10-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_articles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactenquires',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
