# Generated by Django 4.2.4 on 2023-10-09 20:05

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_articlecategory_articles_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='JobPositions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('details', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('last_date', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('skills', models.ManyToManyField(to='Home.skills')),
            ],
        ),
    ]
