# Generated by Django 4.2.4 on 2023-10-09 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_skills_jobpositions'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpositions',
            name='experiance',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jobpositions',
            name='salary',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobpositions',
            name='sub_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobpositions',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
