# Generated by Django 4.2.4 on 2023-10-10 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_jobpositions_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpositions',
            name='uid',
        ),
    ]
