# Generated by Django 4.2.4 on 2023-10-10 17:17

import Home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_remove_jobpositions_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpositions',
            name='uid',
            field=models.CharField(default=Home.models.generate_uid, editable=False, max_length=6),
        ),
    ]
